{% set name = "flexpolyline" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flexpolyline-{{ version }}.tar.gz
  sha256: 69dde225ff91c66c0f6f80044c5fa3e82d905d725608cb99d087c2bb3aeedbbd

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - flexpolyline
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://here.com
  summary: Flexible Polyline encoding a lossy compressed representation of a list of coordinate pairs or triples
  dev_url: https://github.com/heremaps/flexible-polyline
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sackh
